// src/lib/compliments.ts

// Array of compliments and affirmations for Amy
export const compliments = [
	"Your strength as a mother inspires everyone around you.",
	"The way you fight for your children shows a love that has no bounds.",
	"Your laugh is absolutely contagious - it brightens even the darkest day.",
	"Your resilience through life's trials is nothing short of remarkable.",
	"You have a gift for making people feel seen and valued.",
	"The way you maintain your faith through challenges is truly inspiring.",
	"Your honesty about life's struggles makes others feel less alone.",
	"How you balance everything on your plate is amazing to witness.",
	"Your sense of humor turns ordinary moments into cherished memories.",
	"The wisdom in your words often stays with me long after our conversations.",
	"Your capacity for growth and healing shows incredible character.",
	"You show up authentically, even when it would be easier not to.",
	"Your ability to find joy in simple moments is a beautiful gift.",
	"The kindness you show others, even in your own difficult times, is remarkable.",
	"Your determination to keep moving forward, no matter what, is extraordinary.",
	"The love you pour into your children is shaping beautiful human beings.",
	"You have an incredible eye for finding beauty in unexpected places.",
	"The way you prioritize faith in your family is creating a powerful legacy.",
	"Your strength doesn't come from never falling - it comes from rising every time you fall.",
	"You've shown me what courage looks like in real, everyday moments.",
	"The warmth you bring to friendships makes people feel instantly at home.",
	"Your journey toward health and healing inspires others to take that path too.",
	"The way you navigate complicated emotions with honesty is refreshing.",
	"Your willingness to be vulnerable creates space for real connection.",
	"The grace you extend to others (and hopefully yourself) is a beautiful gift.",
	"You handle life's curveballs with a remarkable blend of grit and grace.",
	"Your perseverance through difficult seasons reveals your incredible character.",
	"You bring light into rooms simply by being your authentic self.",
	"The depth of your care for others shows a truly beautiful heart.",
	"Your journey is changing lives around you, even when you can't see it.",
];
