// src/lib/compliments.ts

// Personalized compliments and affirmations for Amy
export const compliments = [
	"Your strength as a mom is fierce, protective, and full of grace — exactly what God cherishes.",
	"The way you fight for Pierson, Paxton, and Presli is a daily testimony of unshakable love.",
	"Your laugh cuts through chaos like light through clouds — it brings real comfort and joy.",
	"You're still standing after everything — that's not just resilience, that's divine grit.",
	"You make people feel known, safe, and understood just by being yourself.",
	"The way you cling to faith through legal battles, parenting storms, and emotional waves is sacred.",
	"Your honesty about anxiety, depression, and pain gives others permission to be real too.",
	"You juggle kids, court dates, school schedules, and still offer kindness — it’s astonishing.",
	"Your humor is dark, clever, and healing — it's your weapon and your balm.",
	"Conversations with you stick with me — your insight comes from a soul that's lived deeply.",
	"You're healing in real-time, and it's changing more than just your own story.",
	"You never fake it — and that courage to be raw is rare and powerful.",
	"Your ability to find joy in thrifting, memes, or quiet moments is something I deeply admire.",
	"Even when you're worn thin, you still look out for others — that’s true strength.",
	"Your refusal to quit, no matter how hard it gets, is proof of a warrior heart.",
	"The love you pour into your kids is shaping resilient, kind, and faith-filled humans.",
	"You spot hidden beauty — in people, places, even pain — and that’s a holy gift.",
	"Your faith sets the foundation for a legacy your children will stand on one day.",
	"Your strength is in the rising, not the pretending — and you rise every single time.",
	"You've shown me what real bravery looks like — not loud, but steady and unshakable.",
	"Being around you feels like being home — safe, seen, and loved just as I am.",
	"Your health journey is more than weight loss — it’s spiritual, emotional, and courageous.",
	"You don't shy away from deep emotions — you face them and grow through them.",
	"Your vulnerability makes room for others to stop hiding and start healing.",
	"You give grace even when you don’t have much to spare — that’s what makes it real.",
	"You meet life’s messiness with grit, faith, and a sarcastic grin — and it's amazing.",
	"Even in your lowest moments, your character speaks louder than your circumstances.",
	"Being near you brings light — not flashy, just steady, quiet, and real.",
	"You care in ways that leave a mark — the deep, eternal kind that God smiles on.",
	"You might not always feel it, but your journey is deeply impacting the people around you.",
];
